language: node_js
sudo: required
node_js:
  - "8.6"
services:
  - postgresql
before_script:
  - psql -c 'create database postit_test;' -U postgres
install:
  - npm install
script:
  - npm test
after_success:
  - npm run coveralls
