export const SIGNUP = 'SIGNUP';
export const SIGNUP_FULFILLED = 'SIGNUP_FULFILLED';
export const SIGNUP_REJECTED = 'SIGNUP_REJECTED';
export const SIGNIN = 'SIGNIN';
export const SIGNIN_FULFILLED = 'SIGNIN_FULFILLED';
export const SIGNIN_REJECTED = 'SIGNIN_REJECTED';
